# The browser's explicit, stable wire-key table is also the C++ source of truth.
set_property(DIRECTORY APPEND PROPERTY CMAKE_CONFIGURE_DEPENDS web/protocol_keys.mjs)
file(READ "${CMAKE_CURRENT_SOURCE_DIR}/web/protocol_keys.mjs" _input_keys)
string(REGEX MATCHALL "\\[[0-9]+, \"[A-Za-z0-9]+\", \"[A-Za-z0-9]+\"\\]" _input_rows "${_input_keys}")
set(_input_cpp "// Generated from web/protocol_keys.mjs. Do not edit.\n")
set(_input_ids)
set(_input_names)
foreach(row IN LISTS _input_rows)
    string(REGEX REPLACE "\\[([0-9]+), \"[A-Za-z0-9]+\", \"([A-Za-z0-9]+)\"\\]" "\\1;\\2" fields "${row}")
    list(GET fields 0 id)
    list(GET fields 1 name)
    if(id LESS 1 OR id GREATER 127 OR id IN_LIST _input_ids OR name IN_LIST _input_names)
        message(FATAL_ERROR "Invalid/duplicate input wire key: ${row}")
    endif()
    list(APPEND _input_ids "${id}")
    list(APPEND _input_names "${name}")
    string(APPEND _input_cpp "{${id}, RenderKey::${name}},\n")
endforeach()
file(MAKE_DIRECTORY "${CMAKE_CURRENT_BINARY_DIR}/generated")
file(WRITE "${CMAKE_CURRENT_BINARY_DIR}/generated/protocol_keys.inc" "${_input_cpp}")
