# libdatachannel v0.24.5, including immutable submodule objects.
if(CMAKE_VERSION VERSION_LESS 3.21)
    message(FATAL_ERROR "WebRTC's bundled libsrtp requires CMake >= 3.21")
endif()
FetchContent_Declare(libdatachannel
    GIT_REPOSITORY https://github.com/paullouisageneau/libdatachannel.git
    GIT_TAG 443f6934d9007eb7076ab7825ba330f355fcbead
    GIT_SUBMODULES deps/plog deps/libsrtp deps/usrsctp)
FetchContent_GetProperties(libdatachannel)
if(NOT libdatachannel_POPULATED)
    FetchContent_Populate(libdatachannel)
endif()
# Scoped normal variables avoid changing the parent project's library policy.
function(render_module_datachannel)
    set(BUILD_SHARED_LIBS ON)
    set(BUILD_SHARED_DEPS_LIBS OFF)
    set(NO_EXAMPLES ON CACHE BOOL "" FORCE)
    set(NO_TESTS ON CACHE BOOL "" FORCE)
    set(LIBSRTP_TEST_APPS OFF CACHE BOOL "" FORCE)
    set(NO_WEBSOCKET ON CACHE BOOL "" FORCE)
    set(NO_MEDIA OFF CACHE BOOL "" FORCE)
    set(USE_NICE ON CACHE BOOL "" FORCE)
    set(USE_GNUTLS OFF CACHE BOOL "" FORCE)
    set(USE_MBEDTLS OFF CACHE BOOL "" FORCE)
    set(USE_SYSTEM_SRTP OFF CACHE BOOL "" FORCE)
    set(USE_SYSTEM_USRSCTP OFF CACHE BOOL "" FORCE)
    set(USE_SYSTEM_PLOG OFF CACHE BOOL "" FORCE)
    add_subdirectory("${libdatachannel_SOURCE_DIR}" "${libdatachannel_BINARY_DIR}" EXCLUDE_FROM_ALL)
    include("${CMAKE_CURRENT_SOURCE_DIR}/cmake/LibDataChannelNiceRelay.cmake")
endfunction()
render_module_datachannel()
add_library(RenderModuleWebRtc SHARED src/webrtc/webrtc_media.cpp src/webrtc/webrtc_session.cpp)
target_compile_features(RenderModuleWebRtc PRIVATE cxx_std_17)
target_include_directories(RenderModuleWebRtc PRIVATE include src)
target_link_libraries(RenderModuleWebRtc PRIVATE RenderModuleVideo datachannel-static Threads::Threads)
target_link_options(RenderModuleWebRtc PRIVATE "-Wl,--exclude-libs,ALL")
set_target_properties(RenderModuleWebRtc PROPERTIES INSTALL_RPATH "$ORIGIN")
if(RENDER_MODULE_BUILD_TESTS)
    target_compile_definitions(RenderModuleWebRtc PRIVATE RENDER_MODULE_WEBRTC_TESTING)
endif()
target_link_libraries(RenderModule PRIVATE RenderModuleWebRtc)
target_compile_definitions(RenderModule PRIVATE RENDER_MODULE_ENABLE_WEBRTC)
install(TARGETS RenderModuleWebRtc EXPORT RenderModuleTargets LIBRARY DESTINATION ${CMAKE_INSTALL_LIBDIR})
install(FILES third_party/WEBRTC_NOTICE.md DESTINATION ${CMAKE_INSTALL_DATADIR}/render-module/licenses)
install(FILES "${libdatachannel_SOURCE_DIR}/LICENSE" DESTINATION ${CMAKE_INSTALL_DATADIR}/render-module/licenses RENAME libdatachannel-LICENSE)
install(FILES "${libdatachannel_SOURCE_DIR}/deps/usrsctp/LICENSE.md" DESTINATION ${CMAKE_INSTALL_DATADIR}/render-module/licenses RENAME usrsctp-LICENSE)
foreach(dep libsrtp plog)
    if(EXISTS "${libdatachannel_SOURCE_DIR}/deps/${dep}/LICENSE")
        install(FILES "${libdatachannel_SOURCE_DIR}/deps/${dep}/LICENSE" DESTINATION ${CMAKE_INSTALL_DATADIR}/render-module/licenses RENAME ${dep}-LICENSE)
    endif()
endforeach()
